# קובץ קונפיגורציה כללי - SkyBlockItems

# --- הגדרות קרב ---
# אם זה true, אביליטיז לא ישפיעו על שחקנים אחרים
disable-abilities-on-players: true

# אם זה true, אביליטיז לא ישפיעו על NPCs
disable-abilities-on-npcs: true

# --- הגדרות מתקדמות ---
# ניתוב הודעות גלובלי (CHAT או ACTION_BAR)
message-routing: CHAT
