name: SkyBlockItems
version: '${project.version}'
main: dev.agam.skyblockitems.SkyBlockItems
api-version: 1.21
depend: [MMOItems, MythicLib]
softdepend: [AuraSkills]
authors: [Agam]
commands:
  skyblockitems:
    description: Main command for SkyBlockItems
    aliases: [sbi]
    usage: /<command> [args]
  skyblockenchants:
    description: Main command for SkyBlockEnchants
    aliases: [se, enchants]
    usage: /<command> [args]
  mmoenchants:
    description: Main command for MMOEnchants
    usage: /<command> [args]
