name: SkyBlockItems
version: '${project.version}'
main: dev.agam.skyblockitems.SkyBlockItems
api-version: 1.21
depend: [MMOItems, MythicLib]
softdepend: [AuraSkills]
authors: [Agam]
commands:
  sbi:
    description: Admin command for SkyBlockItems
    permission: skyblock.admin
  enchant:
    description: Opens the Enchanting GUI
    aliases: [enchants, et]
    permission: skyblock.enchant
  anvil:
    description: Opens the Custom Anvil GUI
    permission: skyblock.anvil