name: SkyBlockItems
version: 1.2.0
main: dev.agam.skyblockitems.SkyBlockItems
api-version: '1.21'
softdepend: [MMOItems, MythicLib, AuraSkills, WorldGuard, PlaceholderAPI, ProtocolLib, NBTAPI]
authors: [Agam]
commands:
  sbi:
    description: Admin command for SkyBlockItems
    permission: skyblock.admin
  enchant:
    description: Opens the Enchanting GUI
    aliases: [enchants, et]
    permission: skyblock.enchant
  anvil:
    description: Opens the Custom Anvil GUI
    permission: skyblock.anvil
  rarity:
    description: Manage item rarities
    permission: skyblockitems.rarity
    aliases: [ir]