name: SkyBlockItems
version: '1.0-SNAPSHOT'
main: dev.agam.skyblockitems.SkyBlockItems
api-version: 1.21
depend: [MMOItems, MythicLib]
softdepend: [AuraSkills]
authors: [Agam]
commands:
  skyblockitems:
    description: Main command for SkyBlockItems
    aliases: [sbi, se, enchants, mmoe, skyblockenchants, mmoenchants]
  ir:
    description: ItemRarity main command
    usage: /ir <set|test|reload>
    aliases: [itemrarity]
    permission: ir.admin
